[package]
name = "ark-bn254-ext"
description = "Extensions for the BN254 pairing-friendly elliptic curve"
version.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
include.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
ark-ec.workspace = true
ark-ff.workspace = true
ark-std.workspace = true
ark-bn254.workspace = true
ark-models-ext.workspace = true
ark-serialize.workspace = true

[dev-dependencies]
ark-algebra-test-templates.workspace = true

[features]
default = [ "std" ]
std = [
  "ark-bn254/std",
  "ark-ec/std",
  "ark-ff/std",
  "ark-models-ext/std",
  "ark-serialize/std",
  "ark-std/std",
]
parallel = [
  "ark-ec/parallel",
  "ark-ff/parallel",
  "ark-std/parallel"
]
